Project_TITAN/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('TITAN/', include('TITANAPP.urls'))
]

TITANAPP/urls.py
from django.contrib.auth.views import LoginView
from django.urls import path

from TITANAPP.views import TITAN_Introduce, TitanCreateView, AccountDetailView, AccountUpdateView, AccountDeleteView

app_name = 'TITANAPP'

urlpatterns = [
    path('introduce/', TITAN_Introduce, name='TITAN_Introduce'),
    path('create/', TitanCreateView.as_view(), name='create'),
    path('login/', LoginView.as_view(template_name='TITANAPP/login.html'), name='login'),
    path('logout/', LoginView.as_view(), name='logout'),
    path('detail/<int:pk>', AccountDetailView.as_view(), name='detail'),
    path('update/<int:pk>', AccountUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', AccountDeleteView.as_view(), name='delete'),
 ]

TITANAPP/models.py
from django.db import models

# Create your models here.

class NewModel(models.Model):
    text = models.CharField(max_length=255, null=False)

TITANAPP/forms.py
from django.contrib.auth.forms import UserCreationForm


class AccountCreationForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['username'].disabled = True

TITANAPP/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.http import HttpResponse, HttpResponseRedirect, HttpResponseForbidden
from django.shortcuts import render

# Create your views here.
from django.urls import reverse, reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import CreateView, DetailView, UpdateView, DeleteView

from TITANAPP.forms import AccountCreationForm
from TITANAPP.models import NewModel


@login_required
def TITAN_Introduce (request):
    if request.method == "POST":
        temp = request.POST.get('input_text')
        model_instance = NewModel()
        model_instance.text = temp
        model_instance.save()

        return HttpResponseRedirect(reverse('TITANAPP:TITAN_Introduce'))

    else:
        data_list = NewModel.objects.all()
        return render(request, 'TITANAPP/middle.html',
                      context={'data_list': data_list})



class TitanCreateView(CreateView):
    model = User
    form_class = UserCreationForm
    # lazy 붙인이유: 바로나오는게 아니라 불러와줄때만 사용하기 위해
    success_url = reverse_lazy('TITANAPP:TITAN_Introduce')
    template_name = 'TITANAPP/create.html'


class AccountDetailView(DetailView):
    model = User
    context_object_name = 'target_user'
    template_name = 'TITANAPP/detail.html'


@method_decorator(login_required, 'post')
@method_decorator(login_required, 'get')
class AccountUpdateView(UpdateView):
    model = User
    form_class = AccountCreationForm
    context_object_name = 'target_user'
    success_url = reverse_lazy('TITANAPP:TITAN_Introduce')
    template_name = 'TITANAPP/update.html'


@method_decorator(login_required, 'post')
@method_decorator(login_required, 'get')
class AccountDeleteView(DeleteView):
    model = User
    context_object_name = 'target_user'
    success_url = reverse_lazy('TITANAPP:TITAN_Introduce')
    template_name = 'TITANAPP/delete.html'

TITANAPP/templates/TITANAPP/create.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}

    <div class="text-center mw-500 m-auto">
        <div class="m-5">
            <h4>Sign Up</h4>
        </div>
        <div>
            <form action="{% url 'TITANAPP:create' %}" method="post">
                {% csrf_token %}
                {% bootstrap_form form %}
                <div style="margin-top: 2rem;">
                    <input type="submit"
                           class="btn btn-dark rounded-pill px-5">
                </div>
            </form>
        </div>
    </div>


{% endblock %}

TITANAPP/templates/TITANAPP/delete.html
{% extends 'base.html' %}

{% block content %}

    <div class="text-center mw-500 m-auto">
        <div class="m-5">
            <h4>Quit</h4>
        </div>
        <div>
            <form action="{% url 'TITANAPP:delete' pk=target_user.pk %}" method="post">
                {% csrf_token %}
                <div style="margin-top: 2rem;">
                    <input type="submit"
                           class="btn btn-danger rounded-pill px-5">
                </div>
            </form>
        </div>
    </div>


{% endblock %}

TITANAPP/templates/TITANAPP/detail.html
{% extends 'base.html' %}

{% block content %}

    <div class="text-center mw-500 m-auto">
        <div class="m-5">
            <h4>{{ target_user.username }}</h4>
        </div>
        <div>
            {{ target_user.date_joined }}
        </div>

        {% if user == target_user %}

        <div>
            <a href="{% url 'TITANAPP:update' pk=target_user.pk %}">
                Update Info
            </a>
        </div>
        <div>
            <a href="{% url 'TITANAPP:delete' pk=target_user.pk %}">
                Quit
            </a>
        </div>

        {% endif %}

    </div>


{% endblock %}

TITANAPP/templates/TITANAPP/login.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}


    <div class="text-center mw-500 m-auto">
        <div class="m-5">
            <h4>Login</h4>
        </div>
        <div>
            <form action="{% url 'TITANAPP:login' %}" method="post">
                {% csrf_token %}
                {% bootstrap_form form %}
                <div style="margin-top: 2rem;">
                    <input type="submit"
                           class="btn btn-dark rounded-pill px-5">
                </div>
            </form>
        </div>
    </div>


{% endblock %}

TITANAPP/templates/TITANAPP/middle.html
{%  extends 'base.html' %}

{% block content %}


    <div style=" color: white; text-align:center; background-color: black; background-size: 20rem;">
        <h1>HTTP METHOD</h1>

        <form action="/TITAN/introduce/" method="post">
            {% csrf_token %}
            <input type="text" name = "input_text">
            <input type="submit" class="btn btn-outline-light rounded-pill px-5"; >
        </form>
        {% for data in data_list %}

        <h3>{{ data.text }}</h3>

        {% endfor %}
    </div>

{% endblock %}

TITANAPP/templates/TITANAPP/update.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}

    <div class="text-center mw-500 m-auto">
        <div class="m-5">
            <h4>Update Info</h4>
        </div>
        <div>
            <form action="{% url 'TITANAPP:update' pk=target_user.pk %}" method="post">
                {% csrf_token %}
                {% bootstrap_form form %}
                <div style="margin-top: 2rem;">
                    <input type="submit"
                           class="btn btn-dark rounded-pill px-5">
                </div>
            </form>
        </div>
    </div>


{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">

{% include 'head.html' %}



<body style=" font-family: 'NanumSquareR' ">

{% include 'header.html' %}
    <hr>

{% block content %}
{% endblock %}

    <hr>
{% include 'footer.html' %}

</body>
</html>

templates/footer.html
<div class="footer_total">
    <div>
        <span>공지사항</span>
        <span>제휴문의</span>
        <span>서비스 소개</span>
    </div>

    <div class="footer_logo">
        <h5>TITAN</h5>
    </div>


</div>

templates/head.html
{% load static %}

<head>
    <meta charset="UTF-8">
    <title>TITAN</title>

    {# BOOTSTRAP #}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    {# GOOGLE FONT   #}
    {# font-family: 'Baskervville', serif;  #}
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Baskervville&display=swap" rel="stylesheet">

    {# DEFAULT CSS LINK    #}
    <link rel="stylesheet" type="text/css" href="{% static 'base.css' %}">

    <style>
        @font-face {
            font-family: 'NanumSquareR';
            src: local('NanumSquareR'),
            url("{% static 'fonts/NanumSquareR.otf' %}") format("opentype");
        }
        @font-face {
            font-family: 'NanumSquareEB';
            src: local('NanumSquareEB'),
            url("{% static 'fonts/NanumSquareEB.otf' %}") format("opentype");
        }
        @font-face {
            font-family: 'NanumSquareB';
            src: local('NanumSquareB'),
            url("{% static 'fonts/NanumSquareB.otf' %}") format("opentype");
        }
        @font-face {
            font-family: 'NanumSquareL';
            src: local('NanumSquareL'),
            url("{% static 'fonts/NanumSquareL.otf' %}") format("opentype");
        }
    </style>

</head>

templates/header.html
<div class = "header_total">

    <div  class = "header_logo">
        <h1>TITAN</h1>
    </div>

</div>

<div class="header_menu">
    <span type="button" class="btn btn-outline-secondary"> 봄 </span>
    <span type="button" class="btn btn-outline-secondary">  여름 </span>
   {% if not user.is_authenticated %}
    <span type="button" class="btn btn-outline-secondary">
        <a href="{% url 'TITANAPP:login' %}">
            Login
        </a>
    </span>
    <span type="button" class="btn btn-outline-secondary">
        <a href="{% url 'TITANAPP:create' %}">
            Sing up
        </a>
    </span>
    {% else %}
    <span type="button" class="btn btn-outline-secondary">
        <a href="{% url 'TITANAPP:logout' %}">
            Logout
        </a>
    </span>
    <span type="button" class="btn btn-outline-secondary">
        <a href="{% url 'TITANAPP:detail' pk=user.pk %}">
            Mypage
        </a>
    </span>
    {% endif %}
</div>